INSERT INTO  USERS
	( NAME, SURNAME ) VALUES ( 'Name1', 'Surname1' );
INSERT INTO  USERS
	( NAME, SURNAME ) VALUES ( 'Name2', 'Surname1' );
INSERT INTO  USERS
	( NAME, SURNAME ) VALUES ( 'Name3', 'Surname1');
INSERT INTO  USERS
	( NAME, SURNAME ) VALUES ( 'Name4', 'Surname1' );
INSERT INTO  USERS
	( NAME, SURNAME ) VALUES ( 'Name5', 'Surname1' );
	
INSERT INTO  ALIASES
	( ALIAS, USER_ID) VALUES ( 'Name1', (SELECT c.ID FROM USERS c WHERE c.NAME = 'Name1'));
INSERT INTO  ALIASES
	( ALIAS, USER_ID) VALUES ( 'Name_1', (SELECT c.ID FROM USERS c WHERE c.NAME = 'Name1'));
INSERT INTO  ALIASES
	( ALIAS, USER_ID) VALUES ('Name2', (SELECT c.ID FROM USERS c WHERE c.NAME = 'Name2'));
INSERT INTO  ALIASES
	( ALIAS, USER_ID) VALUES ( 'Name3', (SELECT c.ID FROM USERS c WHERE c.NAME = 'Name3'));
INSERT INTO  ALIASES
	( ALIAS, USER_ID) VALUES ( 'Name4', (SELECT c.ID FROM USERS c WHERE c.NAME = 'Name4'));