INSERT INTO  USERS
( NAME, SURNAME ) VALUES ( 'Name1', 'Surname1' );
INSERT INTO  USERS
( NAME, SURNAME ) VALUES ( 'Name2', 'Surname1' );
INSERT INTO  USERS
( NAME, SURNAME ) VALUES ( 'Name3', 'Surname1');
INSERT INTO  USERS
( NAME, SURNAME ) VALUES ( 'Name4', 'Surname1' );
INSERT INTO  USERS
( NAME, SURNAME ) VALUES ( 'Name5', 'Surname1' );

INSERT INTO  ALIASES
( ALIAS, USER_ID, COMMITS) VALUES ( 'Name1', (SELECT c.ID FROM USERS c WHERE c.NAME = 'Name1'), 132);
INSERT INTO  ALIASES
( ALIAS, USER_ID, COMMITS) VALUES ( 'Name_1', (SELECT c.ID FROM USERS c WHERE c.NAME = 'Name1'), 465);
INSERT INTO  ALIASES
( ALIAS, USER_ID, COMMITS) VALUES ('Name2', (SELECT c.ID FROM USERS c WHERE c.NAME = 'Name2'),87 );
INSERT INTO  ALIASES
( ALIAS, USER_ID, COMMITS) VALUES ( 'Name3', (SELECT c.ID FROM USERS c WHERE c.NAME = 'Name3'),5);
INSERT INTO  ALIASES
( ALIAS, USER_ID, COMMITS) VALUES ( 'Name4', (SELECT c.ID FROM USERS c WHERE c.NAME = 'Name4'),798);
INSERT INTO  ALIASES
( ALIAS, USER_ID, COMMITS) VALUES ( 'Name5', (SELECT c.ID FROM USERS c WHERE c.NAME = 'Name5'),122);