INSERT INTO  USERS
	( NAME, SURNAME ) VALUES ( 'Name1', 'Surname1' );
INSERT INTO  CONTACTS
	( NAME, SURNAME ) VALUES ( 'Name2', 'Surname1' );
INSERT INTO  CONTACTS
	( NAME, SURNAME ) VALUES ( 'Name3', 'Surname1');
INSERT INTO  CONTACTS
	( NAME, SURNAME ) VALUES ( 'Name4', 'Surname1' );
INSERT INTO  CONTACTS
	( NAME, SURNAME ) VALUES ( 'Name5', 'Surname1' );
	
INSERT INTO  ALIASES
	( ALIAS) VALUES ( 'Name1', (SELECT c.ID FROM CONTACTS c WHERE c.CONTACT_ID = 'Contact1'));
INSERT INTO  ORDERS
	( ALIAS) VALUES ( 'Name_1', (SELECT c.ID FROM CONTACTS c WHERE c.CONTACT_ID = 'Contact2'));
INSERT INTO  ORDERS
	( ALIAS) VALUES ('Name2', (SELECT c.ID FROM CONTACTS c WHERE c.CONTACT_ID = 'Contact3'));
INSERT INTO  ORDERS
	( ALIAS) VALUES ( 'Name3', (SELECT c.ID FROM CONTACTS c WHERE c.CONTACT_ID = 'Contact3'));
INSERT INTO  ORDERS
	( ALIAS) VALUES ( 'Name4', (SELECT c.ID FROM CONTACTS c WHERE c.CONTACT_ID = 'Contact4'));